services:
  - type: web
    name: medguard-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: mongo_url
        sync: false
      - key: database_name
        sync: false
      - key: jwt_secret
        sync: false
      - key: jwt_algorithm
        sync: false
      - key: access_token_expire_minutes
        sync: false
